server:
  port: 8080
  max-http-header-size: 65536
  error:
    path: "/not-found"
spring:
  data:
    rest:
      base-path: /api
  cache:
    type: redis
  config.use-legacy-processing: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    serialization-inclusion: NON_EMPTY
    default-property-inclusion: NON_EMPTY
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/changelog.yml
    defaultSchema: public
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      cache:
        use_second_level_cache: false
        use_query_cache: false
      ddl-auto: none
      hibernate:
        show_sql: true
        format_sql: true
  # datasource Config
  datasource:
    primary:
      driver-class-name: org.postgresql.Driver
      jdbcURL: jdbc:postgresql://localhost:5432/mylibrary
      username: mylibrary
      password: password1
    liquibase:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/mylibrary
      username: mylibrary
      password: password1
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
